config/routes.rb
Curso::Application.routes.draw do
  get "inicio/index"

  resources :horarios

  resources :asignaturas do
    resources :estudiantes
  end  

  root :to => 'inicio#index'    

  resources :materias

  resources :instructores

end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
	has_many :estudiantes
	has_many :horarios
  attr_accessible :ficha, :nombre_asignatura 

  validate :nombre_asignatura,  :presence => true, :length => {:maximum => 70}
  validate :ficha, :presence => true, :uniqueness => true, :length => {:maximum => 70}

  def self.search(search)
  	if search
  	   where('nombre_asignatura like ?',"%#{search}%")
  	else
  		scoped
  	end	
  end
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  
  before_filter :find_asignatura, :exeption => [:index, :create, :new]
  helper_method :sort_column, :sort_direction

  def index

    @nxp = (params[:registro] != nil)? params[:registro].to_i : 3

    if ((@nxp) <= 0)
      @nxp = 3
    end

    @asignaturas = Asignatura.order(sort_column + ' ' + sort_direction).search(params[:search]).page(params[:page]).per_page(@nxp)

    respond_to do |format|
      format.html # index.html.erb
      format.xml{render :xml => @asignaturas}
      #format.json { render json: @asignaturas }
    end
  end

  def show 
    @asignatura = Asignatura.find(params[:id])
  end

  def new
    @asignatura = Asignatura.new
  end

  def edit
    @asignatura = Asignatura.find(params[:id])
  end

  def create
    @asignatura = Asignatura.new(params[:asignatura])
    render :action => :new unless @asignatura.save
  end

  def update
    @asignatura = Asignatura.find(params[:id])
    render :action => :edit unless @asignatura.update_attributes(params[:asignatura])
  end

  def destroy
    @asignatura = Asignatura.find(params[:id])
    @asignatura.destroy
  end  

  private
  def find_asignatura
    @asignatura = Asignatura.find(params[:id]) if params[:id]
  end

  def sort_column
    Asignatura.column_names.include?(params[:sort]) ? params[:sort] : "nombre_asignatura"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_asignatura.html.erb
<tr id=<%= "asignatura_#{asignatura.id}" %>>

	<td><%= link_to 'estudiantes', asignatura_estudiantes_path(asignatura), :class => 'btn btn-mini btn-info'%></td>
	
	<td><%= asignatura.nombre_asignatura %></td>
	<td><%= asignatura.ficha %></td>	

	<td>
		<%= link_to 'Mostrar', asignatura, :remote => true, :class => 'btn btn-mini' %>
        <%= link_to 'Editar', edit_asignatura_path(asignatura), :remote => true, :class => 'btn btn-mini' %>
        <%= link_to 'Eliminar', asignatura,  :data => { :confirm => 'Esta Seguro?' }, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
	</td>
</tr>	

app/views/asignaturas/_form.html.erb
<%= simple_form_for(@asignatura, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>

  <%= f.input :nombre_asignatura, :label => "Nombre asignatura",  :required => true %>
  <%= f.input :ficha, :label => "Ficha",  :required => true %>
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', asignaturas_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/asignaturas/_show.html.erb
<%- model_class = Asignatura -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='asignatura'>
  <p><%= @asignatura.nombre_asignatura %></p>
  <p><%= @asignatura.ficha %></p>
</div>

app/views/asignaturas/create.js.erb
$('table tbody').append("<%= escape_javascript(render @asignatura) %>")
$.lazybox.close()

app/views/asignaturas/destroy.js.erb
$("table tr#asignatura_<%= @asignatura.id %>").remove();

app/views/asignaturas/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/asignaturas/index.html.erb
<%- model_class = Asignatura -%>
<div class="page-header">
  <h1>Cursos</h1>
</div>

<%= form_tag request.path, :method => 'get' do %>
    <p>Nombre Curso:</p>
    <p><%= text_field_tag :search, params[:search] %></p>
   
    <p>numero de registros
    <p><%= text_field_tag :registro, params[:registro]%></p>

    <p><%= submit_tag "Consultar", :nombre_asignatura => nil, :class => 'btn btn-small btn-success' %></p>
<% end %> 

<br/> 
<table class="table table-striped table-bordered table-condensed pretty">
  <thead>
    <tr>
      <th></th>
      <th><%= sortable "nombre_asignatura" %></th>
      <th><%= sortable "ficha" %></th>

    </tr>
  </thead>
  <tbody>
    <%= render @asignaturas %>
  </tbody>
</table>

<tfoot>
  <tr>
    <td><%= link_to 'Nuevo Curso', new_asignatura_path, :remote => true, :class => 'btn btn-small btn-info' %></td>
  </tr> 
</tfoot>

<br/>
<br/>

<div align="center">
  <%= will_paginate @asignaturas, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo:' rescue nil %>
</div>

<p>
  Total Aprendices : <%= @asignaturas.total_entries %>
</p>

app/views/asignaturas/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/asignaturas/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/asignaturas/update.js.erb
$('tr#asignatura_<%= @asignatura.id %>').replaceWith("<%= escape_javascript(render @asignatura) %>")
$.lazybox.close()