config/routes.rb
Curso::Application.routes.draw do
  get "inicio/index"

  resources :horarios

  resources :asignaturas do
    resources :estudiantes
  end  

  root :to => 'inicio#index'    

  resources :materias

  resources :instructores

end

app/models/horario.rb
class Horario < ActiveRecord::Base
  belongs_to :materia
  belongs_to :instructor
  belongs_to :asignatura
  attr_accessible :aula, :dia, :hora, :materia_id, :instructor_id, :asignatura_id

  validate :aula, :presence => true, :uniqueness => true, :length => {:maximum => 999} 

  def self.search(search)

  	where('aula like ?', "%#{search}%")
  	
  end

end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController

  helper_method :sort_column, :sort_direction
  def index

    @nxp = (params[:registros] != nil)? params[:registros].to_i : 3

    if ((@nxp) <= 0)
      @nxp = 3
    end

    @horarios = Horario.order(sort_column + ' ' + sort_direction).search(params[:search]).page(params[:page]).per_page(@nxp)

    respond_to do |format|
      format.html # index.html.erb
      format.xml {render :xml => @horarios}
      #format.json { render json: @horarios }
    end
  end

  def show
    @horario = Horario.find(params[:id]) 
    respond_to do |format| 
      format.json { render json: @horario }
      format.pdf do
        pdf = HorarioPdf.new(@horario, view_context)
        send_data  pdf.render, filename:
        "horario_#{@horario.asignatura.nombre_asignatura}.pdf",
        type: "application/pdf"
      end  
    end     
  end

  def new
    @horario = Horario.new
  end

  def edit
    @horario = Horario.find(params[:id])
  end

  def create
    @horario = Horario.new(params[:horario])
    render :action => :new unless @horario.save
  end

  def update
    @horario = Horario.find(params[:id])
    render :action => :edit unless @horario.update_attributes(params[:horario])
  end

  def destroy
    @horario = Horario.find(params[:id])
    @horario.destroy
  end

  private
  def sort_column
    Horario.column_names.include?(params[:sort]) ? params[:sort] : "dia"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/views/horarios/_form.html.erb
<%= simple_form_for(@horario, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>
  <tr>
    <%= f.error_notification %>
    <p><%= f.input :dia, :label => "Dia", :required => true  %></p>
    <p><%= f.input :hora, :label => "Hora", :required => true %></p>
    <p><%= f.input :aula, :label => "Aula", :required => true %></p>

    <p><%= f.label :materia_id %></p>
    <p><%= f.collection_select :materia_id, Materia.all, :id, :nombre_materia, prompt: "Materias" %></p>

    <p><%= f.label :instructor_id %></p>
    <p><%= f.collection_select :instructor_id, Instructor.all, :id, :nombre, prompt: "Instructores" %></p>

    <p><%= f.label :asignatura_id %></p>
    <p><%= f.collection_select :asignatura_id, Asignatura.all, :id, :nombre_asignatura, prompt: "Cursos" %></p>
  </tr>

  <div class="form-actions">
    <%= f.submit "Guardar", :class => 'btn btn-primary' %>
    <%= link_to 'Atras', horarios_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/horarios/_horario.html.erb
<tr id=<%="horario_#{horario.id}"%>>

	<td><%= horario.dia %></td>
	<td><%= horario.hora %></td>
	<td><%= horario.aula %></td>
	<td><%= horario.materia.nombre_materia %></td>
	<td><%= horario.instructor.nombre %></td>
	<td><%= horario.asignatura.nombre_asignatura%></td>
	<td><%= horario.created_at%></td>
	<td>
		<%= link_to 'Mostrar', horario, :remote => true, :class => 'btn btn-mini' %>
		<%= link_to 'Editar', edit_horario_path(horario), :remote => true, :class => 'btn btn-mini' %>
		<%= link_to 'Eliminar',horario, :data => {:confirm => 'Esta Seguro?'}, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
		<%= link_to "PDF", horario_path(horario, :format => "pdf"), :class => 'btn btn-mini btn-info' %>
	</td>
</tr>

app/views/horarios/_show.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1>Horarios</h1>
</div>

<div class="horario">
  <p><%= @horario.dia %></p>
  <p><%= @horario.hora %></p>
  <p><%= @horario.aula %></p>
  <p><%= @horario.materia.nombre_materia %></p>
  <p><%= @horario.instructor.nombre %></p>
  <p><%= @horario.asignatura.nombre_asignatura %></p>
</div>

app/views/horarios/create.js.erb
$('table tbody').apped("<%= escape_javascript(render @horario) %>")
$.lazybox.close();

app/views/horarios/destroy.js.erb
$("table tr#horario_<%= @horario.id %>").remove();

app/views/horarios/edit.js.erb
$.lazybox("<%= j( render :partial => 'form') %>",{niceCose :true});

app/views/horarios/index.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1>Horarios</h1>
</div>

<%= form_tag request.path, :method => 'get' do%>
 
    <p>Horario:</p>
    <p><%= text_field_tag :search, params[:search] %></p>

    <p>numero de registros:</p>
    <p><%= text_field_tag :registros, params[:registros] %></p>

    <p><%= submit_tag "Consultar", :aula => nil, :class => 'btn btn-small btn-success' %></p>
<% end %>  

<br/>  

<table class=" span10 table table-striped table-bordered table-condensed pretty">
  <thead>
    <tr>
      <th><%= sortable "dia" %></th>
      <th><%= sortable "hora" %></th>
      <th><%= sortable "aula" %></th>
      <th><%= sortable "materia_id","Materia" %></th>
      <th><%= sortable "instructor_id","Instructor" %></th>
      <th><%= sortable "curso_id","Curso" %></th>
      <th><%= sortable "created_at","Creado en" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @horarios %>
  </tbody>
</table>

<tfoot>
  <tr>
    <td><%= link_to 'Nuevo Horario', new_horario_path, :remote => true, :class => 'btn btn-small btn-info' %></td>
  </tr>
</tfoot>

<br/>
<br/>

<div>
  <%= will_paginate @horarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;'%>
</div>

<p>
  Total Horarios: <%= @horarios.total_entries %>
</p>

app/views/horarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/horarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg :true, klass: 'sticker', fixed: true })

app/views/horarios/update.js.erb
$('tr#horario_<%= @horario.id %>').replaceWith("<%= escape_javascript(render @horario) %>")
$.lazybox.close()