config/routes.rb
Curso::Application.routes.draw do
  get "inicio/index"

  resources :horarios

  resources :asignaturas do
    resources :estudiantes
  end  

  root :to => 'inicio#index'    

  resources :materias

  resources :instructores

end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :asignatura
  attr_accessible :apellido, :cedula, :direccion, :nombre, :telefono, :asignatura_id

  validates :nombre, :presence => true, :length => {:maximum => 80}
  validates :apellido, :presence => true, :length => {:maximum => 80}
  validates :cedula, :presence => true, :uniqueness => true, :length => {:maximum => 18}
  validates :telefono, :presence => true, :uniqueness => true, :length => {:maximum => 20}
  validates :direccion, :presence => true, :uniqueness => true 
  def self.search(search)

  	where('nombre like ?', "%#{search}%")
  	
  end
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController

  before_filter :find_asignatura_estudiante
  helper_method :sort_column, :sort_direction
  def index
    @nxp = (params[:registros] != nil)? params[:registros].to_i : 3
    if ((@nxp) <= 0)
      @nxp = 3
    end
    @estudiantes = @asignatura.estudiantes.order(sort_column + ' ' + sort_direction).search(params[:search]).page(params[:page]).per_page(@nxp)

    respond_to do |format|
      format.html # index.html.erb
      format.xml {render :xml => @estudiantes} 
    end
  end

  def show 
  end

  def new
    @estudiante = Estudiante.new
  end

  def edit 
  end

  def create
    @estudiante = Estudiante.new(params[:estudiante])
    @asignatura = Asignatura.find(params[:asignatura_id])
    @estudiante.asignatura_id = @asignatura.id
    render :action => :new unless @estudiante.save
  end

  def update
    render :action => :edit unless @estudiante.update_attributes(params[:estudiante])
  end

  def destroy
    @estudiante.destroy
  end  

  private
  def find_asignatura_estudiante
    @asignatura = Asignatura.find(params[:asignatura_id])
    @estudiante = Estudiante.find(params[:id]) if params[:id]
  end

  def sort_column
    Estudiante.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_estudiante.html.erb
<tr id=<%= "estudiante_#{estudiante.id}" %>>
	
	<td><%= estudiante.nombre %></td>
	<td><%= estudiante.apellido %></td>
	<td><%= estudiante.cedula %></td>
	<td><%= estudiante.telefono %></td>	
	<td><%= estudiante.direccion %></td>
	<td><%= estudiante.asignatura.nombre_asignatura%></td>

	<td>
		<%= link_to 'Mostrar', asignatura_estudiante_path(@asignatura,estudiante), :remote => true, :class => 'btn btn-mini' %>
        <%= link_to 'Editar', edit_asignatura_estudiante_path(@asignatura,estudiante), :remote => true, :class => 'btn btn-mini' %>
        <%= link_to 'Eliminar', asignatura_estudiante_path(@asignatura,estudiante),  :data => { :confirm => 'Esta Seguro?' }, :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
	</td>
</tr>	

app/views/estudiantes/_form.html.erb
<%= simple_form_for([@asignatura, @estudiante], :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  <%= f.error_notification %>

  <%= f.input :nombre, :label => "Nombre", :required => true  %>
  <%= f.input :apellido, :label => "Apellido", :required => true %>
  <%= f.input :cedula, :label => "Cedula", :required => true %>
  <%= f.input :telefono, :label => "Telefono", :required => true %>
  <%= f.input :direccion, :label => "Direccion", :required => true %>
  
  <div class="form-actions">
    <%= f.submit "Guardar", :class => 'btn btn-small btn-info' %>
    <%= link_to "Atras", asignatura_estudiantes_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/estudiantes/_show.html.erb
<%- model_class = Estudiante -%>
<div class="page-header">
  <h1>Estudiantes</h1>
</div>

<div class='estudiante'>
  <p><%= @estudiante.nombre %></p>
  <p><%= @estudiante.apellido %></p>
  <p><%= @estudiante.cedula %></p>
  <p><%= @estudiante.telefono %></p>
  <p><%= @estudiante.direccion %></p>
  <p><%= @estudiante.asignatura.nombre_asignatura%></p>
</div

app/views/estudiantes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()

app/views/estudiantes/destroy.js.erb
$('table tr#estudiante_<%= @estudiante.id %>').remove();

app/views/estudiantes/edit.js.erb
$.lazybox("<%= j( render :partial => 'form') %>",{niceClose:true});

app/views/estudiantes/index.html.erb
<%- model_class = Estudiante -%>
<div class="page-header">
  <h1>Estudiantes del Curso:<%= @asignatura.nombre_asignatura %></h1>
</div>

<%= form_tag request.path, :method => 'get' do %>
    <p>Nombre Estudiante:</p>
    <p><%= text_field_tag :search, params[:search] %></p>
    
    <p>Numero de registros</p>
    <p><%= text_field_tag :registros, params[:registros] %></p>

    <p><%= submit_tag "Consultar", :nombre => nil, :class => 'btn btn-small btn-info' %></p>

<% end %>

<br/>

<table class="table table-striped table-bordered table-condensed pretty ">
  <thead>
    <tr>
      <th><%= sortable "nombre" %></th>
      <th><%= sortable "apellido" %></th>
      <th><%= sortable "cedula" %></th>
      <th><%= sortable "telefono" %></th>
      <th><%= sortable "direccion" %></th>
      <th><%= sortable "asignatura_id", "Curso" %></th>
      <th>Acciones</th>
    </tr>
  </thead>
  </tbody>
      <%= render @estudiantes %>
  </tbody>
</table>

<tfoot>
  <td><%= link_to 'Nuevo estudiante', new_asignatura_estudiante_path,:remote => true, :class => 'btn btn-small btn btn-success' %></td>
  <td><%= link_to "Atras", asignaturas_path, :class => 'btn btn-small btn btn-info' %></td>
</tfoot>

<br/>
<br/>

<div align="center">
  <%= will_paginate @estudiantes, :previous_label => '&laquo; Anterior', :next_label  => 'siguiente&raquo;' %>
</div>

<p>
  Total Aprendices : <%= @estudiantes.total_entries%>
</p>

app/views/estudiantes/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/estudiantes/show.js.erb
$.lazybox("<%= j(render 'show') %>",{closeImg :true, klass: 'sticker', fixed: true})

app/views/estudiantes/update.js.erb
$('tr#estudiante_<%= @estudiante.id %>').replaceWith("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()