config/routes.rb
Curso::Application.routes.draw do
  get "inicio/index"

  resources :horarios

  resources :asignaturas do
    resources :estudiantes
  end  

  root :to => 'inicio#index'    

  resources :materias

  resources :instructores

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	<a class="close" data-dismiss="alert">&#215;</a>
	<%= content_tag :div, msg, :id => "flash_#{name}" %>
	</div>
	<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-pills ">
	<li class="active">
		<%= link_to('Meterias',materias_path) %>
	</li>
	<li>
	    <%= link_to('Instructores', instructores_path)%>
	</li>
	<li>
	    <%= link_to('Cursos',asignaturas_path)%>
	</li>
	<li>
	    <%= link_to('Horarios',horarios_path)%>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
           <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
           </a>
            <div class="nav-collapse">
              <%= render 'layouts/navigation' %>
           </div>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span9">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>